config/routes.rb
Rails.application.routes.draw do

 

  devise_for :admins, skip: [:registrations]
  devise_scope :admins do
  	authenticated :admin do
  		resources :organizers
  		resources :toy_libraries do
  		resources :toy_supplies
  		end
  		resources :toy_requests, only: [:destroy]
  		root to: 'toy_libraries#index', as: :admin_authenticated_root
  	end
  end

  devise_for :organizers, skip: [:registrations]
  devise_scope :organizers do
  	authenticated  :organizer do
  		resources :toy_libraries, except: [:new, :create, :destroy] do
  			resources :toy_supplies, only: [:new, :create]
  			resources :toy_requests, only: [:new, :create]
  		end
  		resources :toy_requests, except: [:new, :create]
  		root to: 'toy_libraries#index', as: :organizer_authenticated_root
  	end
  end
  root to: 'publics#index'
  resources :donations
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :toy_library
  has_many :donation_items, inverse_of: :donation
  
  accepts_nested_attributes_for :donation_items, :reject_if => :all_blank, :allow_destroy => true
end

app/models/donation_item.rb
class DonationItem < ApplicationRecord
  belongs_to :toy_library
  belongs_to :donation
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/toy.rb
class Toy < ApplicationRecord
end

app/models/toy_library.rb
class ToyLibrary < ApplicationRecord
  belongs_to :organizer
  
  has_many :donations
  has_many :donation_items, :through => :donations
end

app/models/toy_request.rb
class ToyRequest < ApplicationRecord
	belongs_to :toy_library
	belongs_to :organizer

	has_many :toy_request_item
	has_many :toys, :through => :toy_request_item, :class_name => 'Toys'

	accepts_nested_attributes_for :toys
	accepts_nested_attributes_for :toy_request_item
end

app/models/toy_request_item.rb
class ToyRequestItem < ApplicationRecord
	belongs_to :toy
	belongs_to :toy_request

	accepts_nested_attributes_for :toy, :reject_if => :all_blank
end

app/models/toy_supply.rb
class ToySupply < ApplicationRecord
  belongs_to :toy_library
  belongs_to :toy
  has_many :toys
  accepts_nested_attributes_for :toys, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	if resource.is_a?(Admin)
  		admin_authenticated_root_path
  	elsif resource.is_a?(Organizer)
  		organizer_authenticated_root_path
  	end
  end

  def after_sign_out_path_for(resource_or_scope)
  	root_path
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  
  def index
  	@donations = Donation.all.order(updated_at: :desc)
  end

  def new
  	@donation = Donation.new
  end

  def create
  	@donation = Donation.new(donation_params)
  	if @donation.save
  		redirect_to donations_path
  	else
  		render :new
  	end
  end

  def show
  end

  private
  def donation_params
    params.require(:donation).permit!
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_action :set_organizer, except: [:index, :new, :create]
  def index
  	@organizers = Organizer.order(updated_at: :desc)
  end

  def new
  	@organizer = Organizer.new
  end

  def create
    @organizer = Organizer.new(organizer_params)
    if @organizer.save
      redirect_to organizers_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @organizer.update(organizer_params)
      redirect_to organizers_path()
    else
      render :edit
    end
  end

  private
    def set_organizer
      @organizer = Organizer.find_by(id: params[:id])
      redirect_to organizers_path if @organizer.nil?
    end
    def organizer_params
      params.require(:organizer).permit!
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  	@current_date = Time.now.strftime('%F')
  end
end

app/controllers/toy_requests_controller.rb
class ToyRequestsController < ApplicationController
	before_action :set_toy_request, except: [:index, :new, :create]
  before_action :set_toy_library, only: [:new, :create]
  before_action :build_toys, only: [:create]

  def index
  	@toy_requests = ToyRequest.order(updated_at: :desc)
  end

  def new
    @toy_request = ToyRequest.new
  end

  def create
    @toy_request = ToyRequest.new(toy_request_params)

    if @toy_request.save
      redirect_to toy_requests_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  	if toy_request.update(toy_request_params)
  		redirect_to toy_requests_path
  	else
  		render :edit
  	end
  end

  def destroy
    if toy_request.status == 'ACTIVE'
      @toy_request.update(status: 'CLOSED')
    else
      @toy_request.update(status: 'ACTIVE')
    end
    redirect_to toy_requests_path
  end

  private
    def set_toy_request
      @toy_request = ToyRequest.find_by(id: params[:id])
      redirect_to toy_requests_path, notice: 'Toy Request not found.' if @toy_request.nil?
    end

    def set_toy_library
      @toy_library = ToyLibrary.find_by(id: [params[:id], params[:toy_library_id]])
      redirect_to toy_libraries_path, notice: 'Toy Library not found.' if @toy_library.nil?
    end

    def toy_request_params
      params.require(:toy_request).permit!
    end

    def build_toys
      if params[:toy_request][:toy_request_items_attributes].present?
        toy_ids = []
        params[:toy_request][:toy_request_items_attributes].each do |k, v|
          if !is_number?(v[:toy_id])
            params[:toy_request][:toy_request_items_attributes][k][:toy_attributes] = { name: v[:toy_id].downcase }
          end
        end
      end
    end

    def is_number? string
      true if Float(string) rescue false
    end
end

app/controllers/toy_supplies_controller.rb
class ToySuppliesController < ApplicationController
    before_action :set_toy_library, only: [:new, :create]
    before_action :build_toys, only: [:create]

    def new
   	 @toy_supply = ToySupply.new
    end

    def edit
   	 @toy_supply = ToySupply.new(toy_supply_params)

    if @toy_supply.save
      redirect_to toy_supply_path
    else
      render :new
    end
    end

    private
   	 def set_toy_library
   		 @toy_library = ToyLibrary.find_by(id: [params[:id], params[:toy_library_id]])
   		 redirect_to toy_libraries_path, notice: 'Toy Library not found.' if @toy_library.nil?
   	 end

   	 def toy_library_params
   		 params.require(:toy_library).permit!
   	 end

   	 def build_toys
   		 if params[:toy_library][:toy_supplies_attributes].present?
   			 toy_ids = []
   			 params[:toy_library][:toy_supplies_attributes].each do |k, v|
   				 if !is_number?(v[:toy_id])
   					 params[:toy_library][:toy_supplies_attributes][k][:toy_attributes] = { name: v[:toy_id].downcase }
   				 end
   			 end
   		 end
   	 end
   	 
   	 def is_number? string
   	   true if Float(string) rescue false
   	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/toy_libraries_helper.rb
module ToyLibrariesHelper
end

app/helpers/toy_requests_helper.rb
module ToyRequestsHelper
end

app/helpers/toy_supplies_helper.rb
module ToySuppliesHelper
end

app/views/donations/_donation_item_fields.html.erb
<div class="nested-fields">
	<%= f.input :toy %>
	<%= f.input :quantity %>
	<%= link_to_remove_association "Remove", f %>
</div>

app/views/donations/_form.html.erb
<%= simple_form_for donation do |f| %>
	<div class="donations">
		<%= f.association :toy_library %>
		<%= f.simple_fields_for :donation_items do |donation_item| %>
		<%= render 'donation_item_fields', :f => donation_item %>
		<% end %>
	</div>
	<div id="links">
		<%= link_to_add_association 'Add Donation', f, :donation_items, class: "btn btn-primary" %>
		<%= f.button :submit, "Save", class: "btn btn-primary" %>
	</div>
<% end %>

app/views/donations/new.html.erb
<h1>Donation</h1>
<div class="row">
	<div class="col">
		<%= render partial: 'form', locals: { donation: @donation } %>
	</div>
</div>

app/views/donations/show.html.erb
<h1>Donation</h1>

<%= link_to "Add Donation", new_donation_path, class: "btn btn-primary" %>

<div class="row">
    <div class="col">
        <% if @donations.blank? %>
            <p>
                <div class="alert alert-info" role="alert">
                    No donations yet. Add one now!
                </div>
            </p>
        <% else %>
            <p class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <th>Library</th>
                        <th>Toy</th>
                        <th>Quantity</th>
                    </thead>
                    <tbody>
                        <% @donations.each do |donation| %>
                            <tr>
                                <td>
                                    <%= toy_library.name %>
                                </td>
                                <td>
                                    <%= donation.toy %>
                                    
                                </td>
                                <td>
                                	<%= donation.quantity %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </p>
        <% end %>
    </div>
</div>

app/views/organizers/_form.html.erb
<%= simple_form_for organizer do |f| %>
    <%= f.input :name, required: true %>
    <%= f.input :email, required: true %>
    <%= f.input :password, required: true %>
    <%= f.input :password_confirmation, required: true %>
    <%= f.button :submit, "Save", class: "btn btn-primary" %>
    <%= link_to "Cancel", organizers_path, class: "btn btn-link" %>
<% end %>

app/views/organizers/edit.html.erb
<h2>Edit Organizer</h2>
<div class="row">
    <div class="col">
        <%= render partial: 'form', locals: { organizer: @organizer } %>
    </div>
</div>

app/views/organizers/index.html.erb
<div class="row">
    <div class="col">
        <%= link_to new_organizer_path, class: "btn btn-primary" do %>
            <i class="glyphicon glyphicon-plus"></i>Add Organizers
        <% end %>
    </div>
</div>

<div class="row">
    <div class="col">
        <% if @organizers.blank? %>
            <p>
                <div class="alert alert-info" role="alert">
                    No organizers yet. Add one now!
                </div>
            </p>
        <% else %>
            <p class="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <th>Name</th>
                        <th>Email</th>
                        <th></th>
                    </thead>
                    <tbody>
                        <% @organizers.each do |organizer| %>
                            <tr>
                                <td>
                                    <%= organizer.name %>
                                </td>
                                <td>
                                    <%= organizer.email %>
                                </td>
                                <td>
                                	<%= link_to "Edit", edit_organizer_path(organizer), class: "btn btn-info" %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </p>
        <% end %>
    </div>
</div>

app/views/organizers/new.html.erb
<h2>New Organizer</h2>
<div class="row">
    <div class="col">
        <%= render partial: 'form', locals: { organizer: @organizer } %>
    </div>
</div>

app/views/organizers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/toy_requests/_form.html.erb
<%= f.simple_fields_for toy_request_item do |toy_request_item| %>
    <%= render 'toy_request_item_fields', :f => toy_request_item %>
    <%= link_to_add_association 'Add Toy', f, :toy_request_items %>
    <%= link_to "Cancel", toy_requests_path, class: "btn btn-link" %>
<% end %>

app/views/toy_requests/_toy_fields.html.erb
<div class="nested-fields">
  <%= f.input :name, :hint => 'how should it be tagged' %>
</div>

app/views/toy_requests/_toy_request_item_fields.html.erb
<div class="nested-fields toy-request-item-fields">
  <div class="toy_from_list">
    <%= f.association :toy, :collection => Toy.all(:order => 'name'), :prompt => 'Choose an existing toy' %>
  </div>
  <%= link_to_add_association 'or create a new toy', f, :toy %>
  <%= link_to_remove_association "remove toy", f %>
</div>

app/views/toy_requests/edit.html.erb
<h1>ToyRequests#edit</h1>
<p>Find me in app/views/toy_requests/edit.html.erb</p>

app/views/toy_requests/index.html.erb
<h3>Toy Requests</h3>

<div class="row">
    <div class="col">
        <% if @toy_requests.blank? %>
            <p>
                <div class="alert alert-info" role="alert">
                    No requests yet.
                </div>
            </p>
        <% else %>
            <p class ="table-responsive">
                <table class="table table-striped">
                    <thead>
                        <th><b>Request for</b></th>
                        <th>Requested Toys</th>
                        <th><b>Last Updated At</b></th>
                        <th></th>
                    </thead>
                    <tbody>
                        <% @toy_requests.each do |toyrequest| %>
                            <tr>
                                <td>
                                    <%= toy_library.name %>
                                </td>
                                <td>
                                    <%= toy_request_items %>
                                </td>
                                <td></td>
                                <td>
                                	<%= link_to "Delete", toy_request_path(toy_request), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you want to delete?" } %>
                                </td>
                            </tr>
                        <% end %>
                    </tbody>
                </table>
            </p>
        <% end %>
    </div>
</div>

app/views/toy_requests/new.html.erb
<h2>New Toy Request</h2>
<div class="row">
    <div class="col">
       <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    		Request Toys For...
  		</a>
    </div>
</div>

app/views/toy_requests/show.html.erb
<div class="row">
    <div class="col">
        <%= link_to "Request Toys for", new_toy_library_toy_request_path(toy_library), class: "btn btn-primary" %>
    </div>
</div>

app/views/toy_supplies/_form.html.erb
<%= simple_fields_for toy_supplies do |toy| %>
	<%= f.association :toy %>
	<%= f.input :quantity %>
	<%= f.button :submit, "Create Toy Library", class: "btn btn-primary" %>
	<%= link_to "Cancel", toy_libraries_path, class: "btn btn-danger" %>
<% end %>

app/views/toy_supplies/edit.html.erb
<h1>ToySupplies#create</h1>
<p>Find me in app/views/toy_supplies/create.html.erb</p>

app/views/toy_supplies/new.html.erb
<h1>Add/Remove Toy Supply</h1>
<div class="row">
    <div class="col">
        <%= link_to "Add/Remove Toy Supply", new_toy_library_toy_supply_path, class: "btn btn-primary" %>
        <br>
        <br>
        <%= link_to "Update Toy Supplies", new_toy_library_toy_supply_path, class: "btn btn-primary" %>
    </div>
</div>