config/routes.rb
Rails.application.routes.draw do

 

  devise_for :admins, skip: [:registrations]
  devise_scope :admins do
  	authenticated :admin do
  		resources :organizers
  		resources :toy_libraries do
  		resources :toy_supplies
  		end
  		resources :toy_requests, only: [:destroy]
  		root to: 'toy_libraries#index', as: :admin_authenticated_root
  	end
  end

  devise_for :organizers, skip: [:registrations]
  devise_scope :organizers do
  	authenticated  :organizer do
  		resources :toy_libraries, except: [:new, :create, :destroy] do
  			resources :toy_supplies, only: [:new, :create]
  			resources :toy_requests, only: [:new, :create]
  		end
  		resources :toy_requests, except: [:new, :create]
  		root to: 'toy_libraries#index', as: :organizer_authenticated_root
  	end
  end
  root to: 'publics#index'
  resources :donations
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :toy_library
  has_many :donation_items, inverse_of: :donation
  
  accepts_nested_attributes_for :donation_items, :reject_if => :all_blank, :allow_destroy => true
end

app/models/donation_item.rb
class DonationItem < ApplicationRecord
  belongs_to :toy_library
  belongs_to :donation
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/toy.rb
class Toy < ApplicationRecord
end

app/models/toy_library.rb
class ToyLibrary < ApplicationRecord
  belongs_to :organizer
  
  has_many :donations
  has_many :donation_items, :through => :donations
end

app/models/toy_request.rb
class ToyRequest < ApplicationRecord
	belongs_to :toy_library
	belongs_to :organizer

	has_many :toy_request_item
	has_many :toys, :through => :toy_request_item, :class_name => 'Toys'

	accepts_nested_attributes_for :toys
	accepts_nested_attributes_for :toy_request_item
end

app/models/toy_request_item.rb
class ToyRequestItem < ApplicationRecord
	belongs_to :toy
	belongs_to :toy_request

	accepts_nested_attributes_for :toy, :reject_if => :all_blank
end

app/models/toy_supply.rb
class ToySupply < ApplicationRecord
  belongs_to :toy_library
  belongs_to :toy
  has_many :toys
  accepts_nested_attributes_for :toys, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
  	if resource.is_a?(Admin)
  		admin_authenticated_root_path
  	elsif resource.is_a?(Organizer)
  		organizer_authenticated_root_path
  	end
  end

  def after_sign_out_path_for(resource_or_scope)
  	root_path
  end
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  
  def index
  	@donations = Donation.all.order(updated_at: :desc)
  end

  def new
  	@donation = Donation.new
  end

  def create
  	@donation = Donation.new(donation_params)
  	if @donation.save
  		redirect_to donations_path
  	else
  		render :new
  	end
  end

  def show
  end

  private
  def donation_params
    params.require(:donation).permit!
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_action :set_organizer, except: [:index, :new, :create]
  def index
  	@organizers = Organizer.order(updated_at: :desc)
  end

  def new
  	@organizer = Organizer.new
  end

  def create
    @organizer = Organizer.new(organizer_params)
    if @organizer.save
      redirect_to organizers_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @organizer.update(organizer_params)
      redirect_to organizers_path()
    else
      render :edit
    end
  end

  private
    def set_organizer
      @organizer = Organizer.find_by(id: params[:id])
      redirect_to organizers_path if @organizer.nil?
    end
    def organizer_params
      params.require(:organizer).permit!
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  	@current_date = Time.now.strftime('%F')
  end
end

app/controllers/toy_libraries_controller.rb
class ToyLibrariesController < ApplicationController
	before_action :set_toy_library, except: [:index, :new, :create]
	def index
    	@toy_libraries = ToyLibrary.all.order(updated_at: :desc)
 	end

  	def new
    	@toy_library = ToyLibrary.new
  	end

  	def create
    	@toy_library = ToyLibrary.new(toy_library_params)

    	# Do some processing

    	if @toy_library.save
      		redirect_to toy_libraries_path
    	else
	      	render :new
    	end
  	end

  	def show
  	end

  	def edit
    	# Same code from show method
  	end

  	def update
    	# Same code from show
    	if @toy_library.update(toy_library_params)
      	redirect_to toy_libraries_path
    	else
      	render :edit
    	end
  	end

  	def destroy
    	# Same code from show method
    	if @toy_library.status == 'ACTIVE'
    		@toy_library.update(status: 'CLOSED')
    	else
    		@toy_library.update(status: 'ACTIVE')
    	end
    	redirect_to toy_libraries_path
  	end

  	private
    def set_toy_library
      @toy_library = ToyLibrary.find_by(id: params[:id])
      redirect_to toy_libraries_path if @toy_library.nil?
    end

    def toy_library_params
      params.require(:toy_library).permit!
    end
end

app/controllers/toy_requests_controller.rb
class ToyRequestsController < ApplicationController
	before_action :set_toy_request, except: [:index, :new, :create]
  before_action :set_toy_library, only: [:new, :create]
  before_action :build_toys, only: [:create]

  def index
  	@toy_requests = ToyRequest.order(updated_at: :desc)
  end

  def new
    @toy_request = ToyRequest.new
  end

  def create
    @toy_request = ToyRequest.new(toy_request_params)

    if @toy_request.save
      redirect_to toy_requests_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  	if toy_request.update(toy_request_params)
  		redirect_to toy_requests_path
  	else
  		render :edit
  	end
  end

  def destroy
    if toy_request.status == 'ACTIVE'
      @toy_request.update(status: 'CLOSED')
    else
      @toy_request.update(status: 'ACTIVE')
    end
    redirect_to toy_requests_path
  end

  private
    def set_toy_request
      @toy_request = ToyRequest.find_by(id: params[:id])
      redirect_to toy_requests_path, notice: 'Toy Request not found.' if @toy_request.nil?
    end

    def set_toy_library
      @toy_library = ToyLibrary.find_by(id: [params[:id], params[:toy_library_id]])
      redirect_to toy_libraries_path, notice: 'Toy Library not found.' if @toy_library.nil?
    end

    def toy_request_params
      params.require(:toy_request).permit!
    end

    def build_toys
      if params[:toy_request][:toy_request_items_attributes].present?
        toy_ids = []
        params[:toy_request][:toy_request_items_attributes].each do |k, v|
          if !is_number?(v[:toy_id])
            params[:toy_request][:toy_request_items_attributes][k][:toy_attributes] = { name: v[:toy_id].downcase }
          end
        end
      end
    end

    def is_number? string
      true if Float(string) rescue false
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/toy_libraries_helper.rb
module ToyLibrariesHelper
end

app/helpers/toy_requests_helper.rb
module ToyRequestsHelper
end

app/helpers/toy_supplies_helper.rb
module ToySuppliesHelper
end

app/views/toy_libraries/_form.html.erb
<%#= simple_form_for @post, url: posts_path, method: :post do |f| %>
<%= simple_form_for toy_library do |f| %>
	<%= f.input :name %>
	<%= f.association :organizer %>
	<%= f.input :status, collection: ['PENDING', 'ACTIVE', 'CLOSED'] %>
	<%= f.button :submit, "Create Toy Library", class: "btn btn-primary" %>
	<%= link_to "Cancel", toy_libraries_path, class: "btn btn-link" %>
<% end %>

app/views/toy_libraries/edit.html.erb
<h2>Update Toy Library</h2>
<div class="row">
	<div class="col">
		<%= render partial: 'form', locals: { toy_library: @toy_library } %>
	</div>
</div>

app/views/toy_libraries/index.html.erb
<% if admin_signed_in? %>
	<div class="row">
		<div class="col">
			<%= link_to "Add Toy Library", new_toy_library_path, class: "btn btn-primary" %>
		</div>
	</div>
<% elsif organizer_signed_in? %>
	<div class = "row">
		<div class="col">
			<h5>My Libraries</h5>
		</div>
	</div>
<% end %>


<div class="row">
	<div class="col">
		<% if @toy_libraries.blank? %>
			<p>
				<div class="alert alert-info" role="alert">
					No Toy Libraries yet.
				</div>
			</p>
		<% else %>
			<p>
				<div class="table-responsive">
				<table class="table table-striped">
					<thead>
						<th>Name</th>
						<th colspan = "5"></th>
					</thead>
					<tbody>
						<% @toy_libraries.each do |toy_library| %>
							<tr>
								<td>
									<%= toy_library.name %>
								</td>
								<% if admin_signed_in? %>
									<td>
										<% if toy_library.status == 'ACTIVE' %>
											<%= link_to "Add/Remove Toy Supply", new_toy_library_toy_supply_path(toy_library), class: "btn btn-primary" %>
										<% else %>
										<% end %>
									</td>
									<td>
										<%= link_to "Show", toy_library_path(toy_library), class: "btn btn-primary" %>
									</td>
									<td>
										<%= link_to "Edit", edit_toy_library_path(toy_library), class: "btn btn-info" %>
									</td>
									<td>
										<% if toy_library.status == 'ACTIVE' %>
											<%= link_to "Close", toy_library_path(toy_library), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure you to close?" } %>
										<% else %>
											<%= link_to "Open", toy_library_path(toy_library), method: :delete, class: "btn btn-success", data: { confirm: "Are you sure to open?" } %>
									</td>
									<% end %>
								<% elsif organizer_signed_in? %>
									<td>
										<%= link_to "Add/Remove Toy Supply", new_toy_library_toy_supply_path(toy_library), class: "btn btn-primary" %>
									</td>
									<td>
										<%= link_to "Request Toys", toy_request_path(toy_library), class: "btn btn-info" %>
									</td>
									<td>
										<%= link_to "Show", toy_library_path(toy_library), class: "btn btn-success" %>
									</td>
									<td>
										<%= link_to "Edit", edit_toy_library_path(toy_library), class: "btn btn-warning" %>
									</td>
								<% end %>
							</td>
						<% end %>
					</tbody>
				</table>
			</div>
			</p>
		<% end %>
	</div>
</div>

app/views/toy_libraries/new.html.erb
<h2>New Toy Library</h2>
<div class="row">
	<div class="col">
		<%= render partial: 'form', locals: { toy_library: @toy_library } %>
	</div>
</div>

app/views/toy_libraries/show.html.erb
<div class="row">
	<div class="col">
		<h6>
			<strong> Name: </strong> <%= @toy_library.name %> <br> <strong>Organizer :</strong> <%= @toy_library.organizer.name %> <br> <%= @toy_library.status %>
		</h6>
		<h6>
			<%= link_to "Edit", edit_toy_library_path %> | <%= link_to "Back", toy_libraries_path %>
		</h6>
		<h2>
			Toy Supplies <br> <%= link_to "Add/Remove Toy Supply", toy_library_path(@toy_library), class: "btn btn-primary" %>
			<% if @toy_supplies.blank? %>
				<div class="alert alert-info" role="alert">
					<h5>No Supplies yet.</h5>
				</div>
			<% end %>
		</h2>
		<h2>
			Toy Requests <br>
			<% if @toy_requests.blank? %>
				<div class="alert alert-info" role="alert">
					<h5>No Toy Requests yet.</h5>
				</div>
			<% end %>
		</h2>
	</div>
</div>