config/routes.rb
Rails.application.routes.draw do

 

  devise_for :admins, skip: [:registrations]
  devise_scope :admins do
  	authenticated :admin do
  		resources :organizers
  		resources :toy_libraries do
  		resources :toy_supplies
  		end
  		resources :toy_requests, only: [:destroy]
  		root to: 'toy_libraries#index', as: :admin_authenticated_root
  	end
  end

  devise_for :organizers, skip: [:registrations]
  devise_scope :organizers do
  	authenticated  :organizer do
  		resources :toy_libraries, except: [:new, :create, :destroy] do
  			resources :toy_supplies, only: [:new, :create]
  			resources :toy_requests, only: [:new, :create]
  		end
  		resources :toy_requests, except: [:new, :create]
  		root to: 'toy_libraries#index', as: :organizer_authenticated_root
  	end
  end
  root to: 'publics#index'
  resources :donations
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/donation.rb
class Donation < ApplicationRecord
  belongs_to :toy_library
  has_many :donation_items, inverse_of: :donation
  
  accepts_nested_attributes_for :donation_items, :reject_if => :all_blank, :allow_destroy => true
end

app/models/donation_item.rb
class DonationItem < ApplicationRecord
  belongs_to :toy_library
  belongs_to :donation
end

app/models/organizer.rb
class Organizer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/toy.rb
class Toy < ApplicationRecord
end

app/models/toy_library.rb
class ToyLibrary < ApplicationRecord
  belongs_to :organizer
  
  has_many :donations
  has_many :donation_items, :through => :donations
end

app/models/toy_request.rb
class ToyRequest < ApplicationRecord
	belongs_to :toy_library
	belongs_to :organizer

	has_many :toy_request_item
	has_many :toys, :through => :toy_request_item, :class_name => 'Toys'

	accepts_nested_attributes_for :toys
	accepts_nested_attributes_for :toy_request_item
end

app/models/toy_request_item.rb
class ToyRequestItem < ApplicationRecord
	belongs_to :toy
	belongs_to :toy_request

	accepts_nested_attributes_for :toy, :reject_if => :all_blank
end

app/models/toy_supply.rb
class ToySupply < ApplicationRecord
  belongs_to :toy_library
  belongs_to :toy
  has_many :toys
  accepts_nested_attributes_for :toys, :reject_if => :all_blank, :allow_destroy => true
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  
  def index
  	@donations = Donation.all.order(updated_at: :desc)
  end

  def new
  	@donation = Donation.new
  end

  def create
  	@donation = Donation.new(donation_params)
  	if @donation.save
  		redirect_to donations_path
  	else
  		render :new
  	end
  end

  def show
  end

  private
  def donation_params
    params.require(:donation).permit!
  end
end

app/controllers/organizers_controller.rb
class OrganizersController < ApplicationController
  before_action :set_organizer, except: [:index, :new, :create]
  def index
  	@organizers = Organizer.order(updated_at: :desc)
  end

  def new
  	@organizer = Organizer.new
  end

  def create
    @organizer = Organizer.new(organizer_params)
    if @organizer.save
      redirect_to organizers_path
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @organizer.update(organizer_params)
      redirect_to organizers_path()
    else
      render :edit
    end
  end

  private
    def set_organizer
      @organizer = Organizer.find_by(id: params[:id])
      redirect_to organizers_path if @organizer.nil?
    end
    def organizer_params
      params.require(:organizer).permit!
    end
end

app/controllers/publics_controller.rb
class PublicsController < ApplicationController
  def index
  	@current_date = Time.now.strftime('%F')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donation_helper.rb
module DonationHelper
end

app/helpers/organizers_helper.rb
module OrganizersHelper
end

app/helpers/publics_helper.rb
module PublicsHelper
end

app/helpers/toy_libraries_helper.rb
module ToyLibrariesHelper
end

app/helpers/toy_requests_helper.rb
module ToyRequestsHelper
end

app/helpers/toy_supplies_helper.rb
module ToySuppliesHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Philippine Toy Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="container">
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <% if admin_signed_in? %>
              <li class="nav-item navbar-text text-muted">
                Logged in as <b>Admin</b>
              </li> 
              <li class="nav-item" style="margin-left: 10px">
                <%= link_to "Log out", destroy_admin_session_path, method: :delete, class: "btn btn-danger" %>
              </li>
            <% elsif organizer_signed_in? %>
              <li class="nav-item navbar-text text-muted">
                Logged in as <b>Organizer</b>
              </li>
              <li class="nav-item" style="margin-left: 10px">
                <%= link_to "Log out", destroy_organizer_session_path, method: :delete, class: "btn btn-danger" %>
              </li>
            <% end %>
          </ul>
          <h3>
                <%= link_to "Philippine Toy Library", root_path, class: " nav-link text-muted"%>
          </h3>
          <ul class = "nav nav-pills float-left">
              
              <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "Organizers", organizers_path, class: "nav nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Toy Libraries", toy_libraries_path, class: "nav nav-link" %>
              </li>
              <% elsif organizer_signed_in? %>
              <li class = "nav-item">
                <%= link_to "My Toy Libraries", toy_libraries_path, class: "nav nav-link" %>
              </li>
              <li class = "nav-item">
                <%= link_to "My Requests", toy_requests_path, class: "nav nav-link" %>
              </li>
              <% end %>
            </ul>
          </div>
        </nav>

        <%= yield %>
      </div>
          
      </div>
  </body>
</html>